# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

trigger:
  paths:
    exclude:
    - .github/*
    - .vs/*
  branches:
    include:
    - master

pool: 
  name: Drivers-NIBuildFarm-RFMIBUILD

stages:
- stage: PrepareBuild
  jobs:
  - job: BuildInformation
    steps:
    - powershell: |
        if ("$(Build.Reason)" -eq "Manual") {
          Write-Host "The pipeline was triggered manually."
        } elseif ("$(Build.Reason)" -eq "PullRequest") {
          Write-Host "The pipeline was triggered by a pull request."
        } else {
          Write-Host "The pipeline was triggered by another reason: $(Build.Reason)"
        }
      displayName: CheckTriggerReason
    - powershell: |
        echo "Hello, world!"
        echo "Build number: $(Build.BuildNumber)" 
        echo "Build ID: $(Build.BuildID)" 
        echo "Build Reason: $(Build.Reason)"
        echo "Build SourceBranch: $(BRANCH_NAME)"
        if ("$(Build.Reason)" -eq "PullRequest") {
          echo "Pull Request ID: $(System.PullRequest.PullRequestId)"
          echo "Pull Request Source Branch: $(System.PullRequest.SourceBranch)"
          echo "Pull Request Target Branch: $(System.PullRequest.TargetBranch)"
          $editedFiles = git diff --name-only $(System.PullRequest.TargetBranch) $(System.PullRequest.SourceBranch)
          Write-Host "Files changed: "  -ForegroundColor Darkblue -BackgroundColor yellow
        }
- stage: UnitTest
  jobs:
  - job: UnitTestforPython
    continueOnError: false
    steps:
    - script: |
          echo "Simulate UnitTest On Python Modules"
      displayName: SimulateUnitTestOnPython
      condition: succeeded()

