# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    exclude:
    - .github/*
    - .vs/*
  branches:
    include:
    - master

pool: 
  name: Drivers-NIBuildFarm-RFMIBUILD

stages:
- stage: PrepareBuild
  jobs:
  - job: BuildInformation
    steps:
    - powershell: |
        echo "Hello, world!"
        echo "Build number: $(Build.BuildNumber)" 
        echo "Build ID: $(Build.BuildID)" 
        echo "Build Reason: $(Build.Reason)"
        echo "Build SourceBranch: $(Build.SourceBranch)".Replace("refs/heads/", "")
        echo "Build SourceBranchName: $(Build.SourceBranchName)"
        $currentBranch = "$(Build.SourceBranch)".Replace("refs/heads/", "")
        $editedFiles = git diff --cached --name-only --diff-filter=ACM master...$currentBranch
        Write-Host "Files changed: "  -ForegroundColor Darkblue -BackgroundColor yellow
- stage: UnitTest
  jobs:
  - job: UnitTestforPython
    continueOnError: false
    steps:
    - script: |
          echo "Simulate UnitTest On Python Modules"
      displayName: SimulateUnitTestOnPython
      condition: succeeded()

